UseMetrics: true
CheckForUpdates: true
DownloadUpdates: true
DecraftEnchants: true
UseLuckAttribute: true
EnchantmentDecraftChance: .20
PercentOfEnchantmentsDecrafted: .20
DesmeltTimer: true
BlacklistedItems:
    Decrafting:
        - "iron_block"
    Desmelting:
        - "gold_nugget"
        - "iron_nugget"
CraftingRecipes:
    DecraftingTable:
        Line1: "iron_ingot|diamond|iron_ingot"
        Line2: "wood|workbench|wood"
        Line3: "wood|wood|wood"
    Desmelter:
        Line1: "iron_ingot|diamond|iron_ingot"
        Line2: "wood|furnace|wood"
        Line3: "wood|wood|wood"