CheckForUpdates: true
DownloadUpdates: true
DecraftEnchants: true
UseLuckAttribute: true
EnchantmentDecraftChance: .20
PercentOfEnchantmentsDecrafted: .20
DesmeltTimer: true
BlacklistedItems:
    Decrafting:
        - "iron_block"
    Desmelting:
        - "gold_nugget"
        - "iron_nugget"